---
title: "Reporte de datos de VICo"
author: "Programa de Enfermedades Infecciosas Emergentes / CES-UVG"
output: 
  flexdashboard::flex_dashboard:
    theme: cosmo
    orientation: rows
    vertical_layout: fill
---

```{r setup, include=FALSE}
# Used packages
library(package = flexdashboard)
library(package = tidyr)
library(package = dplyr)


# Number tables and figures
numbered <- local({
  ref <- data_frame(type = character(0), count = integer(0))
  function(type, title){
    if(!type %in% ref$type) ref <<- rbind(
      ref,
      data_frame(type = type, count = 0)
    )
    ref$count[ref$type == type] <<- ref$count[ref$type == type] + 1
    paste0("**", type, " ", ref$count[ref$type == type], ': ', title, ".**")
  }
})
```




<!-- Tab with general content regarging the surveillance -->
# Contenido general


## First row {data-height=120}

### **Información general del sistema de vigilancia** (detalles en pestaña de [detalles del proyecto](#detalles-del-proyecto))

VICo es una colaboración entre UVG, MSPAS y los
Centros para el Control y la Prevención de Enfermedades de Estados Unidos.
Vigila enfermedad diarreica, respiratoria y febril en hospitales y
centros asistenciales.
La vigilancia comenzó en Santa Rosa en noviembre 2007,
y en Quetzaltenango en febrero 2009 en el hospital
y en julio del mismo año en centros y puestos.




### **Población vigilada** (detalles en pestaña de [áreas de captación](#areas-de-captacion))

**Quetzaltenango**
En el Hospital Regional de Quetzaltenango se incluye a pacientes con enfermedad
respiratoria provenientes de
Quetzaltenango,
Salcajá,
Olintepeque,
San Juan Ostuncalco,
San Mateo,
Concepción Chiquirichapa,
Almolonga,
Cantel,
Zunil
y La Esperanza


**Santa Rosa**
En el Hospital Regional de Cuilapa se incluye personas provenientes de Santa Rosa
(población 350,000 en 2015).
En el Centro de Salud de Nueva Santa Rosa se incluye personas provenientes de ese mismo municipio
(población 38,000 en 2015).


## Second row


### `r numbered("Tabla", "Definiciones de caso")` </br>Resumen de las definiciones de caso utilizadas para capturar casos en cada síndrome vigilado. </br>*Puede consultar las definiciones específicas en la pestaña de cada síndrome.

------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
         Síndrome                                     Hospitalizados                                                                                           Ambulatorios en clínica
--------------------------------------------------  --------------------------------------------------------------------------------------------------------- -------------------------------------------------------------------------------------------------------
<span title="Clic para consultar detalles">          Al menos un signo o síntoma de enfermedad respiratoria y evidencia de infección aguda (todas las edades)  Fiebre documentada ≥ 38ºC con historial de tos o dolor de garganta durante los 14 días previos
[respiratorio](#resumen-de-sindrome-respiratorio)    </br>**o**</br>
*</span>                                             Signos de peligro en niños menores a 5 años

<span title="Clic para consultar detalles">          Reporta 3 o más deposiciones no formadas o líquidas en un período de 24 horas durante los 14 días         Reporta 3 o más deposiciones no formadas o líquidas en un período de 24 horas durante los 14 días
[diarreico](#resumen-de-sindrome-diarreico)          previos a la visita a la emergencia                                                                       previos a la visita a la clínica
</span>

<span title="Clic para consultar detalles">          Fiebre sin una causa aparente con inicio < 7 días antes, al presentarse para recibir atención médica,     Fiebre sin una causa aparente con inicio < 7 días antes, al presentarse para recibir atención médica,
[febril](#resumen-de-sindrome-febril)                </br>**o**</br>                                                                                           </br>**o**</br>
</span>                                              fiebre documentada ≥ 38ºC durante la consulta o durante las 24 horas siguientes al ingreso hospitalario   fiebre documentada ≥ 38ºC durante la consulta o durante las 24 horas siguientes al ingreso hospitalario
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------




<!-- Tab with a summary of the respiratory syndrome surveillance -->
# Resumen de síndrome respiratorio




<!-- Tab with a summary of the diarrheal syndrome surveillance -->
# Resumen de síndrome diarreico




<!-- Tab with a summary of the febrile syndrome surveillance -->
# Resumen de síndrome febril




<!-- Tab with a detail of catchment areas -->
# Áreas de captación




<!-- Tab with a detailed description of the project -->
# Detalles del proyecto




<!-- End of the main report page -->
